environment: dev
replicas_min: 1
replicas_max: 1
cpu_request: 250m
cpu_limit: 500m
memory_limit: 500Mi
gcp_bucket: flex-sykepengesoknad-kvitteringer-dev
env:
  SPRING_PROFILES_ACTIVE: default
  SYKEPENGESOKNAD_FRONTEND_CLIENT_ID: dev-gcp:flex:sykepengesoknad
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: dev-gcp:flex:sykepengesoknad-backend
  TOKENX_IDPORTEN_IDP: https://oidc-ver2.difi.no/idporten-oidc-provider/
