apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-bucket-uploader
  namespace: flex
  labels:
    team: flex
spec:
  gcp:
    buckets:
      - name: flex-kvitteringer-prod
  image: {{ image }}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - https://flex-bucket-uploader.intern.nav.no
  liveness:
    path: /internal/health/liveness
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2000Mi
    requests:
      cpu: 400m
      memory: 1000Mi
  vault:
    enabled: false
  env:
    - name: BUCKET_NAME
      value: flex-kvitteringer-prod
  envFrom:
    - configmap: loginservice-idporten
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: flex-bildeprosessering
      external:
        - host: navnob2c.b2clogin.com
        - host: www.googleapis.com
        - host: storage.googleapis.com
        - host: oauth2.googleapis.com
    inbound:
      rules:
        - application: flex-bildeprosessering
        - application: flex-gateway
        - application: sykepengesoknad-backend
        - application: sykepengesoknad-arkivering-oppgave
          namespace: flex
          cluster: prod-gcp
