apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesoknad-kvitteringer
  namespace: flex
  labels:
    team: flex
spec:
  gcp:
    buckets:
      - name: {{gcp_bucket}}
  image: {{ image }}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: {{cpu_limit}}
      memory: {{memory_limit}}
    requests:
      cpu: {{cpu_request}}
      memory: {{memory_limit}}
  vault:
    enabled: false
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: www.googleapis.com
        - host: storage.googleapis.com
        - host: oauth2.googleapis.com
    inbound:
      rules:
        - application: sykepengesoknad-backend
        - application: sykepengesoknad
        - application: sykepengesoknad-arkivering-oppgave
  env:
    - name: BUCKET_NAME
      value: {{gcp_bucket}}
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
