environment: prod
replicas_min: 2
replicas_max: 3
gcp_bucket: flex-kvitteringer-prod
env:
  SPRING_PROFILES_ACTIVE: default
  SYKEPENGESOKNAD_FRONTEND_CLIENT_ID: prod-gcp:flex:sykepengesoknad
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: prod-gcp:flex:sykepengesoknad-backend
  TOKENX_IDPORTEN_IDP: https://oidc.difi.no/idporten-oidc-provider/
