environment: prod
replicas_min: 2
replicas_max: 3
cpu_request: 200m
cpu_limit: 800m
memory_limit: 1000Mi
gcp_bucket: flex-sykepengesoknad-kvitteringer-prod
env:
  SPRING_PROFILES_ACTIVE: default
  SYKEPENGESOKNAD_FRONTEND_CLIENT_ID: prod-gcp:flex:sykepengesoknad
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: prod-gcp:flex:sykepengesoknad-backend
  TOKENX_IDPORTEN_IDP: https://oidc.difi.no/idporten-oidc-provider/
