environment: prod
replicas_min: 2
replicas_max: 3
cpu: 400m
memory: 1280Mi
gcp_bucket: flex-sykepengesoknad-kvitteringer-prod
env:
  SPRING_PROFILES_ACTIVE: default
  SYKEPENGESOKNAD_FRONTEND_CLIENT_ID: prod-gcp:flex:sykepengesoknad
  SYKEPENGESOKNAD_BACKEND_CLIENT_ID: prod-gcp:flex:sykepengesoknad-backend
