server:
  port: 8080

spring:
  main.banner-mode: 'off'
  profiles:
    active: default

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: health,prometheus
    path-mapping.prometheus: /prometheus