apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-bucket-uploader
  namespace: flex
  labels:
    team: flex
spec:
  gcp:
    buckets:
      - name: flex-reisetilskudd-kvitteringer
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - https://flex-bucket-uploader.dev.intern.nav.no
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: false
  webproxy: true
  envFrom:
    - configmap: loginservice-idporten
  azure:
    application:
      enabled: true
      tenant: "trygdeetaten.no"
  accessPolicy:
    outbound:
      rules:
        - application: flex-bildeprosessering
      external:
        - host: navtestb2c.b2clogin.com
        - host: www.googleapis.com
        - host: storage.googleapis.com
        - host: oauth2.googleapis.com
    inbound:
      rules:
        - application: flex-bildeprosessering
        - application: flex-gateway
        - application: syfosoknad
          namespace: flex
          cluster: dev-fss
        - application: syfogsak
          namespace: flex
          cluster: dev-fss
